### ISSUE TITLE
Insert custom Command issues

### ISSUE THREAD

**Issue by MancioDellaVega** [deadlydog/AHKCommandPicker#2]
Hi, 
if i put this code in the file Mycommands.ahk 

AddCommand("shortNameFunction","Name_Function","description Explore path D:\Downloads")
Name_Function()
{
	Run, D:\Downloads
}

the list box show me this
shortNameFunction => Name_Function

instead of show me 
shortNameFunction =>  description Explore path D:\Downloads

I'm sorry for my english i tried to explain...

but this command in the file defaultcommands.ahk works fine and show me in the listbox
WindowCloseAll => Closes all open windows

AddNamedCommand("WindowCloseAll", "CloseAllWin", "Closes all open windows")
CloseAllWin()
{
	MatchList = AutoHotKey Help, Any Other Window Names To Leave Open

	WinGet, ID, List, , , Program Manager
	Loop, %ID%
	{
		StringTrimRight, This_ID, ID%A_Index%, 0
		WinGetTitle, This_Title, ahk_id %This_ID%
		If This_Title in %MatchList%
			Continue
		WinClose, %This_Title%
	}
}

**Comment by deadlydog** [comment]
Hey @MancioDellaVega it looks like you just need to change `AddCommand` to `AddNamedCommand` in the line:

> AddCommand("shortNameFunction","Name_Function","description Explore path D:\Downloads")

You can read the docs on the difference between AddCommand and AddNamedCommand [here](https://github.com/deadlydog/AHKCommandPicker/blob/master/docs/GettingStarted.md#adding-new-commands)

I believe that should solve your issue. If not, feel free to reopen this issue.

**Comment by MancioDellaVega** [comment]
> Hey @MancioDellaVega it looks like you just need to change `AddCommand` to `AddNamedCommand` in the line:
> 
> > AddCommand("shortNameFunction","Name_Function","description Explore path D:\Downloads")
> 
> You can read the docs on the difference between AddCommand and AddNamedCommand [here](https://github.com/deadlydog/AHKCommandPicker/blob/master/docs/GettingStarted.md#adding-new-commands)
> 
> I believe that should solve your issue. If not, feel free to reopen this issue.

ooops thanks, I'm sorry you are right my mistake...
